---
- ansible.builtin.include_vars: '{{ item }}'
  name: set OS dependent variables
  tags:
  - prereq
  with_first_found:
  - '{{ ansible_distribution }}_{{ ansible_distribution_major_version }}.yml'
  - '{{ ansible_distribution }}.yml'
  - '{{ ansible_os_family }}_{{ ansible_distribution_major_version }}.yml'
  - '{{ ansible_os_family }}.yml'
  - default.yml
- ansible.builtin.include_tasks: rsyslog.yml
  name: configure rsyslog
  when: syslog_implementation == 'rsyslog'
- ansible.builtin.include_tasks: syslog-ng.yml
  name: configure syslog-ng
  when: syslog_implementation == 'syslog-ng'
