---
- name: Set OS dependent variables
  ansible.builtin.include_vars: "{{ item }}"
  tags:
    - prereq
  with_first_found:
    - "{{ ansible_distribution }}_{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}_{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_os_family }}.yml"
    - default.yml
- name: Configure rsyslog
  ansible.builtin.include_tasks: rsyslog.yml
  when: syslog_implementation == 'rsyslog'
- name: Configure syslog-ng
  ansible.builtin.include_tasks: syslog-ng.yml
  when: syslog_implementation == 'syslog-ng'
