---
- name: rsyslog | Deploy rsyslog config for clients
  ansible.builtin.template:
    src: rsyslog-remote.conf.j2
    dest: "{{ syslog_conf_path }}/sentinel.conf"
    owner: root
    group: root
    mode: "0644"
  become: true
  notify:
    - Restart rsyslog
    - Send magic message
