---
- name: syslog-ng | Deploy syslog-ng config for clients
  ansible.builtin.blockinfile:
    block:
      'destination d_sentinel { tcp( "{{ sentinel_syslog_server }}" port( {{
      sentinel_syslog_port }} )); };

      log { source(src); destination(d_sentinel); };

      '
    path: /etc/syslog-ng/syslog-ng.conf
  notify:
    - Restart syslog
    - Send magic message
